language: python

sudo: false
python:
  - 2.7

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

  allow_failures:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install "pexpect>=3.3" pyflakes pytest epydoc rlipython

script:
  - set -e
  - set -x
  - pytest --doctest-modules lib tests
